// src/components/GamePage/Crane/Crane.tsx
import React, { CSSProperties } from 'react';
import { useSelector } from 'react-redux';
import { GlobalState } from '../../../redux/Store';

import BG from './images/Crane.png';

import './Crane.css';
import { breaks } from '../../../util/misc';

const Crane: React.FC = () => {
  const client = useSelector((state: GlobalState) => state.client);
  const animated = useSelector((state: GlobalState) => state.animated);

  // Calculate where to put them
  let left = client.width / 2 - 600 * (2 / 3) - 7; // DESKTOP
  if (client.width < breaks.sm) {
    left = client.width / 2 - 698 / 2; // MOBILE
  }

  const style: CSSProperties = {
    left: `${left}px`,
    zIndex: animated.isActive ? 20 : 0
  };

  return <img src={BG} draggable="false" alt="Crane" className="crane" style={style} />;
};

export default Crane;

// src/lib/components/Crane.svelte
<script lang="ts">
	import { animatedStore } from '../stores/animatedStore';
	import { clientStore } from '../stores/clientStore';
	import { breaks } from '../util/misc';

	$: left =
		$clientStore.width < breaks.sm
			? $clientStore.width / 2 - 698 / 2 // MOBILE
			: $clientStore.width / 2 - 600 * (2 / 3) - 7; // DESKTOP

	$: style = `
        left: ${left}px;
        zIndex ${$animatedStore.isActive ? 20 : 0};
    `;
</script>

<img src="/images/Crane.png" draggable="false" alt="Crane" class="crane" {style} />;

<style>
	.crane {
		position: absolute;
		bottom: 60px;
		left: 0px;
		width: 800px;
		z-index: 9;
	}
</style>
