// src/components/GamePage/VictoryPopup/VictoryPopup.tsx
import React, { CSSProperties } from 'react';
import { motion } from 'framer-motion';
import { useSelector } from 'react-redux';
import { GlobalState } from '../../../redux/Store';
import { strings } from '../../../util/language';

import Trophy from './images/Trophy.png';

import './VictoryPopup.css';

const VictoryPopup: React.FC = () => {
  const moveCount = useSelector((state: GlobalState) => state.history.length);
  const client = useSelector((state: GlobalState) => state.client);
  const { language } = useSelector((state: GlobalState) => state.settings);

  const popupStyle: CSSProperties = {
    left: `${client.width / 2 - 157}px`,
    top: `${client.height / 2 - 302}px`
  };

  const animate = {
    filter: ['saturate(5)', 'saturate(0)', 'saturate(5)'],
    rotate: [-5, 0, 5],
    scale: [1.2, 1, 1.2],
    x: [5, 5, 5],
    y: [-25, -25, -25]
  };

  const transition = {
    duration: 1,
    yoyo: Infinity
  };

  return (
    <>
      <div className="popup" style={popupStyle}>
        <motion.img
          draggable="false"
          src={Trophy}
          alt="Trophy"
          className="trophy"
          animate={animate}
          transition={transition}
        />
        <p>
          {strings[language].gamepage.victory[0]}
          <b>{moveCount}</b>
          {strings[language].gamepage.victory[1]}
        </p>
      </div>
    </>
  );
};

export default VictoryPopup;

// src/lib/components/VictoryPopup.svelte
<script lang="ts">
	import { clientStore } from '../stores/clientStore';
	import { historyStore } from '../stores/historyStore';
	import { settingsStore } from '../stores/settingsStore';
	import { strings } from '../util/language';
	import { elasticOut } from 'svelte/easing';

	$: moveCount = $historyStore.length;
	$: language = $settingsStore.language;
	$: popupStyle = `
        left: ${$clientStore.width / 2 - 157}px;
		top: ${$clientStore.height / 2 - 302}px;
    `;

	const spin = (node: any, { duration }: { duration: number }) => {
		return {
			duration,
			css: (t: number) => {
				const eased = elasticOut(t);

				return `
                    animation-iteration-count: infinite;
					transform: scale(${eased}) rotate(${eased * 1080}deg);
					color: hsl(
						${Math.trunc(t * 360)},
						${Math.min(100, 1000 - 1000 * t)}%,
						${Math.min(50, 500 - 500 * t)}%
					);`;
			}
		};
	};
</script>

<div class="popup" style={popupStyle}>
	<img
		transition:spin={{ duration: 800 }}
		draggable="false"
		src="/images/Trophy.png"
		alt="Trophy"
		class="trophy"
	/>
	<p>
		{strings[language].gamepage.victory[0]}
		<b>{moveCount}</b>
		{strings[language].gamepage.victory[1]}
	</p>
</div>

<style>
	.popup {
		position: absolute;
		background-color: rgba(255, 255, 255, 0.9);
		border-radius: 25px;
		color: black;
		padding: 25px;
		width: 264px;
		text-align: center;
		z-index: 50; /* Definitely above all */
	}

	.trophy {
		width: 100%;
		height: 100%;
	}
</style>
